version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ".:/app"
    ports:
      - "8000:80"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/todo"
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
